name: YTCraft
version: '${project.version}'
main: mod.zenith.ytcraft.YTCraft
api-version: '1.20'
commands:
  YTSettings:
    description: "Settings for YTCraft Plugin."


  YTCraft:
    description: "Starts or Ends YTCraft Session."
    usage: "/ytcraft [start,end]"
    alias:  ["yt"]